# Generated by Django 4.2.2 on 2023-06-11 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brew',
            name='abv',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('occasion', models.CharField(choices=[('S', 'Sports Viewing'), ('P', 'Party'), ('O', 'Outdoor Event'), ('G', 'Get-Together'), ('F', 'Formal Event'), ('I', 'Individual Consumption'), ('O', 'Other')], default='S', max_length=1)),
                ('brew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.brew')),
            ],
        ),
    ]
