# Generated by Django 4.2.2 on 2023-06-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_snack_alter_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='brew',
            name='snacks',
            field=models.ManyToManyField(to='main_app.snack'),
        ),
    ]
